# Generated by Django 5.2.1 on 2025-06-04 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('area_of_residence', models.CharField(choices=[('Hindi', 'Hindi'), ('Sabasaba', 'Sabasaba'), ('Kiongoni', 'Kiongoni'), ('Matengeni', 'Matengeni'), ('Safirisi', 'Safirisi')], max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('profile_image', models.URLField(blank=True, default='https://res.cloudinary.com/dc68huvjj/image/upload/v1748119193/zzy3zwrius3kjrzp4ifc.png', null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='farmlinkApp.farmer')),
            ],
        ),
    ]
