# Generated by Django 5.2.1 on 2025-06-20 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmlinkApp', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_orders_farmer', to='farmlinkApp.farmer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='farmlinkApp.product')),
                ('seller_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_orders_seller', to='farmlinkApp.farmer')),
            ],
        ),
    ]
