# Generated by Django 5.2.1 on 2025-06-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmlinkApp', '0005_farmerpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='expo_token',
            field=models.CharField(default='qOE08EA5OCq-yL323EhTY8', max_length=200),
        ),
    ]
